[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#4287f5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif" 